---
# 上传文件配置

default:
  # 名称
  name            : 普通文件
  # 类型
  type            : local
  # 文件存储目录
  root_dir        : uploadfiles
  # 文件下载入口
  root_url        : http://localhost:3000/uploadfiles/files
  # 最大上传文件大小
  max_size        : 4MB
  # 支持文件类型
  mime_type       : !!seq
    - image/png
    - image/jpeg
    - image/webp
  # 是否使用源文件名
  original_name   : true
  # 只允许登录用户下载
  download_auth   : true

# 用户头像
avatar:
  # 名称
  name            : 用户头像
  # 类型
  type            : local
  # 文件存储目录
  root_dir        : uploadfiles/avatar
  # 文件下载入口
  root_url        : http://localhost:3000/download/avatar
  # 最大上传文件大小
  max_size        : 4MB
  # 支持文件类型 size
  mime_type       : !!seq
    - image/png
    - image/webp
  # 是否使用源文件名
  original_name   : true
  # 只允许登录用户下载
  download_auth   : false
  # 使用用户目录
  user_dir        : true