
# 默认存储器
default:
  # 名称
  name: 默认
  # 描述
  description: 默认存储器
  # 最大上传文件大小
  max_limit: 4mb
  # 支持文件类型
  mime_types:
    - image/png
    - image/jpeg
    - image/webp
  # 主目录
  root_dir: uploadfiles
  # URL入口
  urlprefix: http://localhost:4000/uploadfiles
  # 使用源文件名称
  original_name: true