
# 账号登录
login:
  - key: username
    type: string
    rules:
      - required: true
        message: 用户名不能为空
        code: 1000
  - key: password
    type: string
    rules:
      - required: true
        message: 密码不能为空
        code: 1000

# 多账号选择登录
loginSelect:
  - key: uuid
    type: string
    rules:
      - required: true
        message: 缺少登录识别码
        code: 1000
  - key: result
    type: string
    rules:
      - required: true
        message: 缺少登录识别码
        code: 1000

# 设置密码
password:
  - key: password
    type: string
    rules:
      - required: true
        message: 密码不能为空
        code: 1000
      - pattern: !!js/regexp /^(?=.*[A-Za-z])[A-Za-z0-9$@$!%*#?&]{8,20}$/
        message: 密码格式错误
        code: 1000
  - key: verify_id
    type: string
    rules:
      - required: true
        message: 缺少身份验证
        code: 1000

# 设置电子邮箱
email:
  - key: email
    type: string
    rules:
      - required: true
        message: 电子邮箱不能为空
        code: 1000
      - validator: isEmail
        message: 电子邮箱格式错误
        code: 1000
  - key: verify_id
    type: string
    rules:
      - required: true
        message: 缺少身份验证
        code: 1000
  - key: code
    type: string
    rules:
      - required: true
        message: 缺少验证码
        code: 1000

# 设置手机号
mobile:
  - key: mobile
    type: string
    rules:
      - required: true
        message: 手机号不能为空
        code: 1000
      - validator: isMobilePhone
        message: 手机号格式错误
        code: 1000
  - key: verify_id
    type: string
    rules:
      - required: true
        message: 缺少身份验证
        code: 1000
  - key: code
    type: string
    rules:
      - required: true
        message: 缺少验证码
        code: 1000

# 注销账号
remove:
  - key: username
    type: string
    rules:
      - required: true
        message: 账号名称不能为空
        code: 1000
  - key: verify_id
    type: string
    rules:
      - required: true
        message: 缺少身份验证
        code: 1000

# 重置密码（找回密码用）
resetpwd:
  - key: verify_id
    type: string
    rules:
      - required: true
        message: 缺少验证ID
        code: 1000
  - key: code
    type: string
    rules:
      - required: true
        message: 缺少验证码
        code: 1000
  - key: name
    type: string
    rules:
      - required: true
        message: 缺少电子邮箱或手机号
        code: 1000
  - key: password
    type: string
    rules:
      - required: true
        message: 密码不能为空
        code: 1000
      - pattern: !!js/regexp /^(?=.*[A-Za-z])[A-Za-z0-9$@$!%*#?&]{8,20}$/
        message: 密码需要 8 - 20 位的字母、数字和英文符号
        code: 1000

# 注册用户
register:
  - key: username
    type: string
    rules:
      - required: true
        message: 用户名不能为空
        code: 1000
      - pattern: !!js/regexp /^[a-zA-Z]{1}[a-zA-Z0-9\_\-]/
        message: 英文字符开头，支持小写英文、数字、下划线和中划线组合
        code: 1000
      - min: 5
        max: 20
        message: 长度限定 5 - 20 位字符
        code: 1000
  - key: email
    type: string
    rules:
      - required: true
        message: 电子邮箱不能为空
        code: 1000
      - validator: isEmail
        message: 请输入正确的邮箱地址，如 example@163.com
        code: 1000
  - key: password
    type: string
    rules:
      - required: true
        message: 登录密码不能为空
        code: 1000
      - pattern: !!js/regexp /^(?=.*[A-Za-z])[A-Za-z0-9$@$!%*#?&]{8,20}$/
        message: 密码需要 8 - 20 位的字母、数字和英文符号
        code: 1000
  - key: invitation
    type: string

# 验证电子邮箱/手机号
verifyEmailMobile:
  - key: token
    type: string
    rules:
      - require: true
        message: 缺少 Token 凭证
  - key: _id
    type: string

# 获取账号消息通知
notification:
  - key: findname
    type: string
  - key: findtype
    type: string
  - key: update_at
    type: date[]
  - key: page
    type: number
  - key: size
    type: number
  - key: sort
    type: string[]
    defaultValue:
      - update_at
      - desc