

# 创建票据
create:
  - key: name
    type: string
    rules:
      - required: true
        message: 票据名称不能为空
        code: 1000
  - key: type
    type: string
    rules:
      - required: true
        message: 票据类型不能为空
        code: 1000
  - key: stint
    type: number
    rules:
      - required: true
        message: 次数限制不能为空
        code: 1000
    format:
      - type: number
    defaultValue: 1
  - key: last_at
    type: string
    rules:
      - required: true
        message: 失效时间不能为空
        code: 1000
      - validator: isDateString
        message: 失效时间无法解析成时间格式
        code: 1000
    format:
      - type: date
    defaultValue: {{now}}
  - key: setting
    type: map
    rules:
      - validator: isPlainObject
        message: 配置不是个Map对象
        code: 1000
    format:
      - type: map
    defaultValue: {}

# 获取票据列表
list:
  - key: name
    type: string
  - key: type
    type: string
  - key: used
    type: string
    rules:
      - pattern: !!js/regexp /^(true|false)$/
        message: 使用状态必须是个 Boolean 值
        code: 1000
    format:
      - type: map
  - key: expired
    type: string
    rules:
      - pattern: !!js/regexp /^(true|false)$/
        message: 过期状态必须是个 Boolean 值
        code: 1000
    format:
      - type: map
  - key: page
    type: number
  - key: size
    type: number
    
# 编辑票据
edit:
  - key: name
    type: string
    rules:
      - required: true
        message: 票据名称不能为空
        code: 1000
  - key: stint
    type: number
    rules:
      - required: true
        message: 次数限制不能为空
        code: 1000
    format:
      - type: number
    defaultValue: 1
  - key: last_at
    type: string
    rules:
      - required: true
        message: 失效时间不能为空
        code: 1000
      - validator: isDateString
        message: 失效时间无法解析成时间格式
        code: 1000
    format:
      - type: date
    defaultValue: {{now}}
  - key: setting
    type: map
    rules:
      - validator: isPlainObject
        message: 配置不是个Map对象
        code: 1000
    format:
      - type: map
    defaultValue: {}
