---
# 服务器配置


# 设置 Session 名称
session_secret    : nuxt-express-typescript

# 设置 Redis 缓存库
redis:
  host            : 127.0.0.1
  port            : 6397
  db              : 0

# 设置 MongoDB 数据库
mongodb:
  uris            : mongodb://localhost:27017/nuxt-express-typescript
  options:
    useNewUrlParser        : true
    useCreateIndex         : true
    useUnifiedTopology     : true