
# 名称
name: nuxtjs-admin
# 服务器IP
host: 0.0.0.0
# 服务器端口
port: 4000
# secret
secret: kenote-nuxtjs-admin
# Redis
redisOpts:
  host: 127.0.0.1
  port: 6379
  db: 0
# MongoDB
mongoOpts:
  uris: mongodb://localhost:27017/kenote-test-db
  options:
    useNewUrlParser: true
    useCreateIndex: true
    useUnifiedTopology: true
    useFindAndModify: false
# 生产环境下使用 ts-node 运行
tsnode: true
# MetaInfo
metaInfo:
  title: Nuxtjs Admin
  meta:
    - charset: utf-8
    - name: viewport
      content: width=device-width, height=device-height, initial-scale=.5
    - hid: description
      name: description
      content: Management platform using NuxtJS.
  link:
    - rel: icon
      type: image/x-icon
      href: /favicon.ico
