---
# 用户注册配置

# 注册用户是否需要邀请
invitation        : true

# 验证码发送间隔；单位：秒
mailphone_step    : 60

# 邮箱验证相关
email_verify:
  # 激活邮件时效；单位：秒
  timeout         : 43200

# 找回密码相关
lost_pass:
  # 验证码时效；单位：秒
  timeout         : 3600

# 页面标题
page_title:
  '/login'                   : 登录
  '/register'                : 注册
  '/lostpass'                : 找回密码
  '/security/email_verify'   : 邮箱激活

# 安全中心
security:
  - key             : password
    type            : success
    name            : 登录密码
    icon            : el-icon-success success
    description:
      - 安全性高的密码可以使账号更安全。
      - 设置一个包含字母，符号或数字中至少两项且长度超过 8 位的密码。
  - key             : email
    type            : info
    name            : 邮箱验证
    icon            : el-icon-info info
    data:
      name            : 您的邮箱
      format          : !!seq
        - !!js/regexp /\w{4}@/g
        - '****@'
    description:
      title           : 您的绑定邮箱可用于
      content         :
        - 安全管理，密码重置找回
        - 账号使用，邮箱快捷登录
        - 服务通知，反馈等
  - key             : mobile
    type            : info
    name            : 手机验证
    icon            : el-icon-info info
    data            : !!map
      name            : 您的手机
      format          : !!seq
        - !!js/regexp /^(\d{3})\d+(\d{4})$/
        - $1****$2
    description:
      title           : 您的绑定邮箱可用于
      content         :
        - 安全管理，密码重置找回
        - 账号使用，手机快捷登录
        - 服务通知，反馈等
  - key             : remove
    type            : warning
    name            : 注销账号
    icon            : el-icon-warning warning
    description     : 如果您不再使用此账号，可以将其注销。账号成功注销后，其下所有服务、数据及隐私信息将会被删除并将无法恢复