---
  # 频道 我的帐户 配置
  
  # 频道 ID
  id            : 3
  # 频道名称
  name          : 配置中心
  # 频道标识
  label         : setting
  # 频道描述
  description   : 配置中心描述
  # 默认打开页面
  default       : /setting/project/goods/item
  # 频道导航
  navs:
    # 导航分栏 -- 项目管理
    - index         : 3-1
      name          : 项目管理
      icon          : iconfont iconfont icon-gaikuang
      children:
        - index         : /setting/project/goods
          name          : 物品管理
          # 查询器 API
          api:
            method        : get
            url           : /api/v1/proto/{{ channel }}/setting/{{ goods }}