---
# 频道 用户中心 配置

# 频道 ID
id            : 2
# 频道名称
name          : 用户中心
# 频道标识
label         : ucenter
# 频道描述
description   : 管理所有用户的信息，以及登录、注册等等
# 默认打开页面
default       : /ucenter/group
# 频道导航
navs:
  # 导航分栏 -- 用户管理
  - index         : 2-1
    name          : 用户管理
    icon          : iconfont iconfont icon-team
    children:
      - index         : /ucenter/group
        name          : 用户组
        # 表格列配置
        columns:
          - key           : id
            name          : ID
            fixed         : left
            width         : 80
            sortable      : true
          - key           : name
            name          : 角色名称
            width         : 120
            align         : left
          - key           : level
            name          : 权级
            width         : 80
            sortable      : true
          - key           : description
            name          : 描述
            minwidth      : 300
            align         : left
            default       : --
          - key           : actions
            name          : 操作
            fixed         : right
            align         : right
            width         : 240
            emit:
              - key           : edit
                name          : 编辑
                type          : dropdown
                conditions:
                  $or:
                    - __authLevel   : 9999
                    - level:
                        $lt           : 9998
                options:
                  - key           : platform
                    name          : 频道入口
                    conditions:
                      level:
                        $lte          : 9000   
                  - key           : access
                    name          : 访问权限
                    conditions:
                      level:
                        $lte          : 9000
                      platform:
                        $size         : 0
              - key           : delete
                name          : 删除
                type          : danger
                conditions:
                  $and:
                    - level:
                        $lt           : 9998
                    - default       : 
                        $ne           : true
        # 检索选项
        search:
          field         : name
      - index         : /ucenter/user
        name          : 查询用户
        # 表格列配置
        columns:
          - key           : id
            name          : ID
            fixed         : left
            width         : 80
            sortable      : true
          - key           : username
            name          : 用户名
            width         : 120
            align         : left
          - key           : nickname
            name          : 昵称
            width         : 120
            align         : left
            default       : --
          - key           : sex
            name          : 性别
            width         : 80
            format:
              maps          : { 0: 未知, 1: 男, 2: 女 }
          - key           : group
            name          : 角色
            width         : 120
            format:
              result        : name
          - key           : email
            name          : 电子邮箱
            width         : 240
            align         : left
            format:
              regexp        : \w{4}@
              substr        : '****@'
          - key           : mobile
            name          : 手机号
            width         : 120
            align         : left
            format:
              regexp        : ^(\d{3})\d+(\d{4})$
              substr        : '$1****$2'
            default       : --
          - key           : create_at
            name          : 注册时间
            width         : 170
            align         : left
            format:
              function    : dateFormat
              options     : [ 'YYYY-MM-DD HH:mm:ss' ]
            sortable      : true
          - key           : actions
            name          : 操作
            fixed         : right
            align         : right
            minwidth      : 240
            emit:
              - key           : edit
                name          : 编辑
                type          : dropdown
                conditions:
                  $or:
                    - group.level:
                        $lt           : $__authLevel
                    - __authLevel   : 9999
                options:
                  - key           : verify-email
                    name          : 激活邮件
                    conditions:
                      binds:
                        $in           : email
                  - key           : access
                    name          : 访问权限
                    conditions:
                      group.level:
                        $lte          : 9000
              - key           : delete
                name          : 删除
                type          : danger
                options:
                  confirm       : [ '此操作将永久删除该邀请码, 是否继续?', 提示 ]
                conditions:
                  group.level:
                    $lt           : $__authLevel

      - index         : /ucenter/ticket
        name          : 注册邀请
        # 表格列配置
        columns:
          - key           : id
            name          : ID
            fixed         : left
            width         : 80
            sortable      : true
          - key           : name
            name          : 名称
            width         : 150
            align         : left
          - key           : cdkey
            name          : cdKey
            width         : 320
            align         : left
          - key           : $count
            name          : 使用次数
            width         : 80
            options:
              tooltip       : '已使用 / 总次数'
              template      : '{{ uses }} / {{ stint }}'
          - key           : last_at
            name          : 过期时间
            width         : 170
            align         : left
            format:
              function    : dateFormat
              options     : [ 'YYYY-MM-DD HH:mm:ss' ]
            sortable      : true
          - key           : $expired_status
            name          : 过期状态
            width         : 100
            field         : right
            options:
              status        : [ 已过期, 未过期, danger ]
              conditions:
                last_at:
                  $lte          : $now
          - key           : $used_status
            name          : 使用状态
            width         : 100
            field         : right
            options:
              status        : [ 已使用, 可使用, info ]
              conditions:
                $or:
                  - used          : true
                  - last_at:
                      $lte          : $now
          - key           : actions
            name          : 操作
            fixed         : right
            align         : right
            width         : 240
            emit:
              - key           : delete
                name          : 删除
                type          : danger
                options:
                  confirm       : [ '此操作将永久删除该邀请码, 是否继续?', 提示 ]
        # 检索选项
        search:
          field         : name
      - index         : /ucenter/team
        name          : 团队
        # 表格列配置
        columns:
          - key           : id
            name          : ID
            fixed         : left
            width         : 80
            sortable      : true
          - key           : name
            name          : 团队名称
            width         : 120
            align         : left
          - key           : description
            name          : 描述
            minwidth      : 300
            align         : left
            default       : --
          - key           : actions
            name          : 操作
            fixed         : right
            align         : right
            width         : 240
            emit:
              - key           : edit
                name          : 编辑
                type          : dropdown
                options:
                  - key           : platform
                    name          : 频道入口
                  - key           : access
                    name          : 访问权限
                    conditions:
                      platform:
                        $size         : 0
                  - key           : people
                    name          : 成员管理
              - key           : delete
                name          : 删除
                type          : danger
                options:
                  confirm       : [ '此操作将永久删除该团队, 是否继续?', 提示 ]
        # 检索选项
        search:
          field         : name