---
# 页面权限配置

# 项目的配置表
'/setting/project/goods':
  # 访问权限
  access          : 9000
  # 列表
  list            : 9000
  # 创建
  create          : 9000
  # 编辑
  edit            : 9000
  # 删除
  remove          : 9000